feat: Add global env
ko-build/ko pull request #1310
Opened 2024-05-14 12:32 UTC by nmittler

Supports configuring global `env` variables that will be applied to all builds.

Modifies the `builder` function to accept a `buildContext` structure. This will simplify similar modifications in the future.

Fixes #1305

2024-05-14 17:20 UTC, imjasonh requested changes

2024-05-14 17:20 UTC, imjasonh commented on pkg/commands/options/testdata/config/.ko.yaml
> +env: CGO_ENABLED=0
Ko already does some weirdness with `CGO_ENABLED` by default, can you make this something more obviously for testing, like `FOO=bar`, and check that this is set in the build env?

2024-05-14 20:47 UTC, imjasonh submitted a review, later dismissed

2024-05-14 20:58 UTC, imjasonh commented on docs/configuration.md
> +- FOO=foo
```suggestion
- FOO=foo
```

2024-05-14 20:58 UTC, imjasonh approved these changes

2024-05-15 09:28 UTC, cpanato approved these changes
thanks!

2024-05-15 09:28 UTC, merged