feat: add ko test command to build with go test -c
ko-build/ko pull request #1407
Opened 2024-09-25 12:39 UTC by vincent-d

Add a new command to build images with the output of go test -c.

It allows configuring build and LD flags in .ko.yaml with different values for build and test commands for a given importpath.

This is a new attempt at implementing #96 with a separate command.

2024-09-25 15:02 UTC, cpanato requested changes
small comments for now

2024-09-25 15:02 UTC, cpanato commented on pkg/commands/test.go
> +// Copyright 2018 ko Build Authors All Rights Reserved.
```suggestion
// Copyright 2024 ko Build Authors All Rights Reserved.
```

2024-09-25 15:02 UTC, cpanato commented on test/test/dummy_test.go
> +package test
missing the header boilerplate

2024-10-01 10:03 UTC, vincent-d commented on pkg/commands/test.go
> +// Copyright 2018 ko Build Authors All Rights Reserved.
fixed

2025-02-04 16:18 UTC, StevenACoffman commented
Oh noes! This could be helpful!

2025-09-22 04:26 UTC, clementnuss commented
what is missing in this PR?

not being able to compile test binaries with `ko` is a blocker. hope someone finds the time to merge this 🙏🏼

2026-01-21 08:14 UTC, mkilchhofer commented
@vincent-d @cpanato can we reopen this?

2026-04-01 20:53 UTC, mkilchhofer commented
Another friendly ping @vincent-d @cpanato @imjasonh - can we reopen this?

2026-05-06 20:55 UTC, mkilchhofer commented
@vincent-d  @cpanato @imjasonh 

![waiting](https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExNTRyZTU0czFocGdvb3E5OWwzOXZpNG1qNnhhNXZpc24zcTVzMDFxaiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/A6YO96sBmr1te/giphy.gif)

2026-05-07 02:25 UTC, imjasonh commented
Sorry again for the radio silence. This happens sometimes in this project due to its volunteer nature, and the relative maturity/stability of the project. I'm sorry that can also make it painful to contribute features.

If the project is moving too slow, you might consider forking to add this feature and using it "in anger" for a while, to get a feel for where there might be improvements. Since I don't anticipate using the feature myself, it's hard for me to gauge well how this should work, and how it should be implemented. I hope you understand.

If you are determined to contribute this to this project, we'll need to rebase and resolve conflicts, and I'll probably have Copilot take a first pass at a code review, if that's okay.

2026-09-06 01:18 UTC, closed without merging